### ISSUE TITLE
Compile ghc in termux

### ISSUE THREAD

**Issue by chenyulue** [MrAdityaAlok/termux-ghc-cross-compiler#1]
In termux there is a *ghc* package, but it doesn't contain **ghci**.  So I try to compile ghc in termux but fail many times. Compiling **ghc** is a little complicated. After some searching I find your compiling scripts, but according to your instruction, I still have no idea how to compile ghc in termux.

 Where should I put the **ghc** source code after downloading it? 

I try to run `./compile.sh` script, but it gives `./compile.sh: line 17: cd: /home/builder/termux-packages: No such file or directory` error info.

Most importanly, does this script compile **ghc** with **ghci** included? 

Thanks for any information!

**Comment by MrAdityaAlok** [comment]
This ghc will not run in termux. It is to be run on termux CI (x86_64) to cross compile ghc packages for Android. So, please wait 1-2 days until I open a PR in Termux.

I have updated termux ghc which includes `ghci`. It will be available once PR is merged.

**Comment by chenyulue** [comment]
Thanks very much!

**Comment by chenyulue** [comment]
By the way, it would be perfect to have the `cabal-install ` tool available in the termux packages. 

I have compiled the `cabal-install` tool with ghc, but the dependency `resolv` fails to be compiled due to missing the library `libresolv`. In termux packages only `libresolv-wrapper` is available.

**Comment by MrAdityaAlok** [comment]
> By the way, it would be perfect to have the `cabal-install ` tool available in the termux packages. 
> 
> I have compiled the `cabal-install` tool with ghc, but the dependency `resolv` fails to be compiled due to missing the library `libresolv`. In termux packages only `libresolv-wrapper` is available.

I have compiled that too...will be available after PR is merged.
